apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod-1
spec:
  nodeName: explicit-gpus-worker
  containers:
  - name: gpu-test-container
    image: nvidia/cuda:11.0-base
    command: ["sleep", "36000"]
    resources:
      limits:
        nvidia.com/gpu: 1  # Requesting 1 GPU
    securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod-2
spec:
  nodeName: explicit-gpus-worker2
  containers:
  - name: gpu-test-container
    image: nvidia/cuda:11.0-base
    command: ["sleep", "36000"]
    resources:
      limits:
        nvidia.com/gpu: 1  # Requesting 1 GPU
    securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-pod-3
spec:
  nodeName: explicit-gpus-worker2
  containers:
  - name: gpu-test-container
    image: nvidia/cuda:11.0-base
    command: ["sleep", "36000"]
    resources:
      limits:
        nvidia.com/gpu: 1  # Requesting 1 GPU
    securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
