apiVersion: v1
kind: Pod
metadata:
  name: dcgmproftester1
spec:
  restartPolicy: OnFailure
  containers:
    - name: dcgmproftester1
      image: nvcr.io/nvidia/cloud-native/dcgm:3.3.0-1-ubuntu22.04
      command: ["/usr/bin/dcgmproftester12"]
      args: ["--no-dcgm-validation", "-t", "1004", "-d", "300"]
      resources:
        limits:
          nvidia.com/gpu: 1
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]

---
apiVersion: v1
kind: Pod
metadata:
  name: dcgmproftester2
spec:
  restartPolicy: OnFailure
  containers:
    - name: dcgmproftester2
      image: nvcr.io/nvidia/cloud-native/dcgm:3.3.0-1-ubuntu22.04
      command: ["/usr/bin/dcgmproftester12"]
      args: ["--no-dcgm-validation", "-t", "1004", "-d", "300"]
      resources:
        limits:
          nvidia.com/gpu: 1
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]

---
apiVersion: v1
kind: Pod
metadata:
  name: dcgmproftester3
spec:
  restartPolicy: OnFailure
  containers:
    - name: dcgmproftester3
      image: nvcr.io/nvidia/cloud-native/dcgm:3.3.0-1-ubuntu22.04
      command: ["/usr/bin/dcgmproftester12"]
      args: ["--no-dcgm-validation", "-t", "1004", "-d", "300"]
      resources:
        limits:
          nvidia.com/gpu: 1
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]

---
apiVersion: v1
kind: Pod
metadata:
  name: dcgmproftester4
spec:
  restartPolicy: OnFailure
  containers:
    - name: dcgmproftester4
      image: nvcr.io/nvidia/cloud-native/dcgm:3.3.0-1-ubuntu22.04
      command: ["/usr/bin/dcgmproftester12"]
      args: ["--no-dcgm-validation", "-t", "1004", "-d", "300"]
      resources:
        limits:
          nvidia.com/gpu: 1
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
