apiVersion: apps.apps.devzero.io/v1
kind: ResourceAdjustmentPolicy
metadata:
  labels:
    {{- include "zxporter.labels" . | nindent 4 }}
  name: {{ include "zxporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  targetSelector:
    matchLabels:
      {{- include "zxporter.selectorLabels" . | nindent 6 }}
    namespaces:
      - {{ .Release.Namespace }}
  exclusions:
    excludedPods:
  policies:
    metricsSources:
      - prometheus
    frequency: "1m"
    autoApply: false
    lookbackDuration: "1m"
    promUrl: "http://prometheus-service.monitoring.svc.cluster.local:8080"
    pulseUrl: "http://host.docker.internal:9990"
    pidController:
      propertionalGain: "10.0"
      integralGain: "0.04"
      derivativeGain: "1.0"
      antiWindUpGain: "1.0"
      integralDischargeTimeConstant: "1.0"
      lowPassTimeConstant: "2s"
      maxOutput: "1.01"
      minOutput: "-2.15"
    cpuRecommendation:
      sampleInterval: "1m"
      requestPercentile: "99.0"
      marginFraction: "0.15"
      targetUtilization: "0.95"
      historyLength: "5m"
    memoryRecommendation:
      sampleInterval: "1m"
      requestPercentile: "99.0"
      marginFraction: "0.15"
      targetUtilization: "0.95"
      historyLength: "5m"
      oomProtection: true
      oomBumpRatio: "1.2"
    normalization:
      enabled: true
      config: default
  logging:
    level: INFO
    enableAuditLogs: true
