apiVersion: devzero.io/v1
kind: CollectionPolicy
metadata:
  name: default-policy
  namespace: devzero-zxporter
spec:
  targetSelector:
    namespaces: [] # Empty means all namespaces
  exclusions:
    excludedNamespaces:
      - kube-system
      - kube-public
  policies:
    frequency: "30s"
    bufferSize: 1000000
    dakrURL: "https://api.devzero.io/dakr"
