apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-evzero-zxporter-collectionpolicy-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - devzero.io
  resources:
  - collectionpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devzero.io
  resources:
  - collectionpolicies/status
  verbs:
  - get
