apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-prometheus-kube-state-metrics
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.prometheusKubeStateMetrics.type }}
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: kube-state-metrics
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.prometheusKubeStateMetrics.ports | toYaml | nindent 2 }}
