apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-prometheus-kube-state-metrics
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-prometheus-kube-state-metrics
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: kube-state-metrics
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-prometheus-kube-state-metrics'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-prometheus-kube-state-metrics'
  namespace: '{{ .Release.Namespace }}'
