// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfIpKey struct {
	ProcessIdentity struct {
		Pid          uint32
		PidStartTime uint64
		CgroupId     uint64
	}
	Tuple struct {
		Saddr  struct{ Raw [16]uint8 }
		Daddr  struct{ Raw [16]uint8 }
		Sport  uint16
		Dport  uint16
		Family uint16
	}
	Proto uint8
}

type bpfNetflowConfigT struct{ MapIndex int32 }

type bpfTrafficSummary struct {
	RxPackets uint64
	RxBytes   uint64
	TxPackets uint64
	TxBytes   uint64
	Comm      [16]uint8
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	CgroupEgress  *ebpf.ProgramSpec `ebpf:"cgroup_egress"`
	CgroupIngress *ebpf.ProgramSpec `ebpf:"cgroup_ingress"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events                  *ebpf.MapSpec `ebpf:"events"`
	NetflowConfigMap        *ebpf.MapSpec `ebpf:"netflow_config_map"`
	NetworkTrafficBufferMap *ebpf.MapSpec `ebpf:"network_traffic_buffer_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	TRACE_EVENT_FL_TRACEPOINT     *ebpf.VariableSpec `ebpf:"TRACE_EVENT_FL_TRACEPOINT"`
	TRACE_EVENT_FL_TRACEPOINT_BIT *ebpf.VariableSpec `ebpf:"TRACE_EVENT_FL_TRACEPOINT_BIT"`
	IpKeyDummy                    *ebpf.VariableSpec `ebpf:"ip_key_dummy"`
	TrafficSummaryDummy           *ebpf.VariableSpec `ebpf:"traffic_summary_dummy"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events                  *ebpf.Map `ebpf:"events"`
	NetflowConfigMap        *ebpf.Map `ebpf:"netflow_config_map"`
	NetworkTrafficBufferMap *ebpf.Map `ebpf:"network_traffic_buffer_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.NetflowConfigMap,
		m.NetworkTrafficBufferMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	TRACE_EVENT_FL_TRACEPOINT     *ebpf.Variable `ebpf:"TRACE_EVENT_FL_TRACEPOINT"`
	TRACE_EVENT_FL_TRACEPOINT_BIT *ebpf.Variable `ebpf:"TRACE_EVENT_FL_TRACEPOINT_BIT"`
	IpKeyDummy                    *ebpf.Variable `ebpf:"ip_key_dummy"`
	TrafficSummaryDummy           *ebpf.Variable `ebpf:"traffic_summary_dummy"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	CgroupEgress  *ebpf.Program `ebpf:"cgroup_egress"`
	CgroupIngress *ebpf.Program `ebpf:"cgroup_ingress"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.CgroupEgress,
		p.CgroupIngress,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
