nameOverride: dz-prometheus-node-exporter
fullnameOverride: dz-prometheus-node-exporter

resources:
  requests:
    memory: "1Gi"
    cpu: "500m"
  limits:
    memory: "2Gi"

rbac:
  pspEnabled: false

containerSecurityContext:
  allowPrivilegeEscalation: false

service:
  port: 9101
  targetPort: 9101

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9101"
  prometheus.io/path: "/metrics"
