nameOverride: dz-prometheus-node-exporter
fullnameOverride: dz-prometheus-node-exporter

rbac:
  pspEnabled: false

containerSecurityContext:
  allowPrivilegeEscalation: false

service:
  port: 9101
  targetPort: 9101
