{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "zxporter.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zxporter.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      control-plane: controller-manager
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow metrics scraping
  {{- if .Values.networkPolicy.allowMetrics }}
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8443
  {{- end }}
  # Allow health checks
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 8081
  egress:
  # Allow DNS
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
  # Allow Kubernetes API access
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  # Allow DAKR endpoint
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
  # Allow Prometheus access
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.namespace }}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 9090
{{- end }}