{{- if .Values.zxporter.useSecretForToken }}
{{- if or .Values.zxporter.clusterToken .Values.zxporter.patToken }}
apiVersion: v1
kind: Secret
metadata:
  name: devzero-zxporter-token
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.zxporter.clusterToken }}
  CLUSTER_TOKEN: {{ .Values.zxporter.clusterToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.zxporter.patToken }}
  PAT_TOKEN: {{ .Values.zxporter.patToken | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}