{{- if .Values.zxporter.useSecretForToken }}
{{- if or .Values.zxporter.clusterToken .Values.zxporter.patToken }}
# Input credentials Secret (user-managed)
# Contains initial PAT/CLUSTER tokens provided by user
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.zxporter.tokenCredentialsSecretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: zxporter
    app.kubernetes.io/component: credentials
type: Opaque
data:
  {{- if .Values.zxporter.clusterToken }}
  CLUSTER_TOKEN: {{ .Values.zxporter.clusterToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.zxporter.patToken }}
  PAT_TOKEN: {{ .Values.zxporter.patToken | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}