{{- if .Values.zxporter.clusterToken }}
{{- if .Values.zxporter.useSecretForToken }}
apiVersion: v1
kind: Secret
metadata:
  name: devzero-zxporter-token
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  CLUSTER_TOKEN: {{ .Values.zxporter.clusterToken | b64enc | quote }}
{{- end }}
{{- end }}