# Runtime token Secret (system-managed)
# This Secret is created and managed by the zxporter application
# Contains exchanged CLUSTER tokens from PAT exchange process
# NOTE: This template creates an empty Secret placeholder when useSecretForToken=true
# The actual token data is populated by the application code during PAT exchange
{{- if .Values.zxporter.useSecretForToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.zxporter.tokenSecretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: zxporter
    app.kubernetes.io/component: runtime-tokens
type: Opaque
data:
  # Empty by default - will be populated by application during PAT exchange
  # CLUSTER_TOKEN: <base64-encoded-exchanged-token>
{{- end }}