apiVersion: v1
kind: Service
metadata:
  name: {{ include "zxporter.fullname" . }}-mpa
  labels:
    {{- include "zxporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "zxporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: mpa-grpc
      port: {{ .Values.mpaServer.port }}
      targetPort: mpa-grpc
      protocol: TCP
