apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devzero-zxporter
    control-plane: controller-manager
  name: devzero-zxporter-controller-manager-metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: controller-manager
