# ==========================================
# LEADER ELECTION AND BOOTSTRAP PERMISSIONS
# ==========================================
# This role contains permissions needed for:
# 1. Controller leader election coordination
# 2. Metrics server bootstrap installation (entrypoint.sh)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devzero-zxporter
  name: devzero-zxporter-leader-election-role
  namespace: {{ .Values.namespace }}
rules:
  # Leader election coordination
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # Event creation for leader election
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  # ConfigMap access for token persistence and general config
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
{{- if .Values.zxporter.useSecretForToken }}
  # Secret access for cluster token persistence when useSecretForToken is enabled
  
  # General Secret create permission (needed to create runtime token secret)
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  
  # Read-only access to credentials Secret (user-provided PAT/CLUSTER tokens)
  - apiGroups:
      - ""
    resourceNames:
      - {{ .Values.zxporter.tokenCredentialsSecretName }}
    resources:
      - secrets
    verbs:
      - get
  
  # Read/write access to runtime token Secret (exchanged tokens)
  - apiGroups:
      - ""
    resourceNames:
      - {{ .Values.zxporter.tokenSecretName }}
    resources:
      - secrets
    verbs:
      - get
      - patch
      - update
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devzero-zxporter
  name: devzero-zxporter-collectionpolicy-editor-role
rules:
  - apiGroups:
      - devzero.io
    resources:
      - collectionpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - devzero.io
    resources:
      - collectionpolicies/status
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devzero-zxporter
  name: devzero-zxporter-collectionpolicy-viewer-role
rules:
  - apiGroups:
      - devzero.io
    resources:
      - collectionpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - devzero.io
    resources:
      - collectionpolicies/status
    verbs:
      - get
---
# ==========================================
# MAIN CLUSTER ROLE - COMPREHENSIVE PERMISSIONS
# ==========================================
# This ClusterRole contains all permissions needed for:
# 1. Metrics server bootstrap installation (entrypoint.sh phase)
# 2. Runtime monitoring and data collection
# 3. Optional third-party resource monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devzero-zxporter-manager-role
rules:
# ==========================================
# BOOTSTRAP PERMISSIONS (entrypoint.sh)
# ==========================================
# ServiceAccount creation for metrics server
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - watch
# Service creation for metrics server
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - watch
# Deployment creation for metrics server
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - watch
# RBAC creation for metrics server
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
# APIService registration for metrics server
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
  - get
  - list
  - patch
  - update

# ==========================================
# RUNTIME MONITORING PERMISSIONS
# ==========================================
# ConfigMap access for token persistence (UPDATE permission)
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
{{- if .Values.zxporter.useSecretForToken }}
# Secret access for cluster token persistence when useSecretForToken is enabled

# General Secret create permission (needed to create runtime token secret)
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create

# Read-only access to credentials Secret (user-provided PAT/CLUSTER tokens)
- apiGroups:
  - ""
  resourceNames:
  - {{ .Values.zxporter.tokenCredentialsSecretName }}
  resources:
  - secrets
  verbs:
  - get

# Read/write access to runtime token Secret (exchanged tokens)
- apiGroups:
  - ""
  resourceNames:
  - {{ .Values.zxporter.tokenSecretName }}
  resources:
  - secrets
  verbs:
  - get
  - patch
  - update
{{- end }}
# Core Kubernetes resources (READ-ONLY monitoring)
- apiGroups:
  - ""
  resources:
  - endpoints
  - events
  - limitranges
  - namespaces
  - nodes
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - replicationcontrollers
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - nodes/status
  - pods/status
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - create
  - get
  - list
  - patch
  - update
# Apps resources (READ-ONLY monitoring - note: deployments already has write perms above for bootstrap)
- apiGroups:
  - apps
  resources:
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.k8s.io
  resources:
  - verticalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.volcano.sh
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - scheduledsparkapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - datadoghq.com
  resources:
  - extendeddaemonsetreplicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devzero.io
  resources:
  - collectionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devzero.io
  resources:
  - collectionpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - devzero.io
  resources:
  - collectionpolicies/status
  verbs:
  - get
  - patch
  - update
# ==========================================
# OPTIONAL THIRD-PARTY RESOURCES
# ==========================================
# These resources are optional - collectors gracefully handle missing CRDs
# Can be disabled via DisabledCollectors configuration

# Karpenter node provisioning (optional)
- apiGroups:
  - karpenter.sh
  resources:
  - machines
  - nodeclaims
  - nodeoverlays
  - nodepools
  - provisioners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - karpenter.k8s.aws
  resources:
  - awsnodetemplates
  - ec2nodeclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - karpenter.azure.com
  resources:
  - aksnodeclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - karpenter.k8s.gcp
  resources:
  - gcenodeclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - karpenter.k8s.oracle
  resources:
  - ocinodeclasses
  verbs:
  - get
  - list
  - watch
# Other optional third-party integrations
- apiGroups:
  - keda.sh
  resources:
  - clustertriggerauthentications
  - scaledjobs
  - scaledobjects
  - triggerauthentications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - notebooks
  verbs:
  - get
  - list
  - watch
# MPA v2: WorkloadRecommendation CRD for syncing in-cluster recommendations back to control plane
- apiGroups:
  - dakr.devzero.io
  resources:
  - workloadrecommendations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
# RBAC monitoring (READ-ONLY - write permissions declared above for bootstrap)
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  - csinodes
  - csistoragecapacities
  - storageclasses
  - volumeattachments
  verbs:
  - get
  - list
  - watch
---
# ==========================================
# METRICS AUTHENTICATION ROLE
# ==========================================
# Role for authenticating metrics endpoint access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devzero-zxporter-metrics-auth-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devzero-zxporter-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devzero-zxporter
  name: devzero-zxporter-leader-election-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devzero-zxporter-leader-election-role
subjects:
  - kind: ServiceAccount
    name: devzero-zxporter-controller-manager
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devzero-zxporter
  name: devzero-zxporter-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devzero-zxporter-manager-role
subjects:
  - kind: ServiceAccount
    name: devzero-zxporter-controller-manager
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devzero-zxporter-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devzero-zxporter-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: devzero-zxporter-controller-manager
    namespace: {{ .Values.namespace }}
