apiVersion: monitoring.devzero.io/v1
kind: CollectionPolicy
metadata:
  labels:
    app.kubernetes.io/name: zxporter
    app.kubernetes.io/managed-by: kustomize
  name: collectionpolicy-sample
spec:
  # TODO(user): Add fields here
