apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zxporter-netmon.serviceAccountName" . }}
  labels: {{- include "zxporter-netmon.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zxporter-netmon.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zxporter-netmon.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
