name: Kubernetes Compatibility Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}
      testserver_img: ${{ steps.set-image.outputs.testserver_img }}
      stress_img: ${{ steps.set-image.outputs.stress_img }}
    
    steps:
      - name: Set Docker image names
        id: set-image
        run: |
          ZXPORTER_IMG="ttl.sh/$(uuidgen):2h"
          TESTSERVER_IMG="ttl.sh/$(uuidgen):2h"
          STRESS_IMG="ttl.sh/$(uuidgen):2h"
          echo "ZXPORTER_IMG=$ZXPORTER_IMG" >> $GITHUB_ENV
          echo "TESTSERVER_IMG=$TESTSERVER_IMG" >> $GITHUB_ENV
          echo "STRESS_IMG=$STRESS_IMG" >> $GITHUB_ENV
          echo "image=$ZXPORTER_IMG" >> $GITHUB_OUTPUT
          echo "testserver_img=$TESTSERVER_IMG" >> $GITHUB_OUTPUT
          echo "stress_img=$STRESS_IMG" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Build and push Docker images
        run: |
          echo "Building and pushing zxporter image: ${{ env.ZXPORTER_IMG }}"
          make docker-build docker-push IMG=${{ env.ZXPORTER_IMG }}
          
          echo "Building and pushing testserver image: ${{ env.TESTSERVER_IMG }}"
          make testserver-docker-build testserver-docker-push TESTSERVER_IMG=${{ env.TESTSERVER_IMG }}
          
          echo "Building and pushing stress image: ${{ env.STRESS_IMG }}"
          make stress-docker-build stress-docker-push STRESS_IMG=${{ env.STRESS_IMG }}

  test:
    name: Test on K8s ${{ matrix.k8s-version }}
    needs: build
    runs-on: ubuntu-xl
    
    strategy:
      fail-fast: false
      matrix:
        k8s-version:
          - v1.25.16
          - v1.26.15
          - v1.27.16
          - v1.28.15
          - v1.29.14
          - v1.30.8
          - v1.31.6
          - v1.32.3

    steps:
      - name: Set Docker image names
        run: |
          echo "ZXPORTER_IMG=${{ needs.build.outputs.image }}" >> $GITHUB_ENV
          echo "TESTSERVER_IMG=${{ needs.build.outputs.testserver_img }}" >> $GITHUB_ENV
          echo "STRESS_IMG=${{ needs.build.outputs.stress_img }}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          version: v0.27.0
          node_image: kindest/node:${{ matrix.k8s-version }}
          cluster_name: kind-${{ matrix.k8s-version }}
          wait: 120s

      - name: Install Metrics Server
        run: |
          helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
          helm repo update
          helm upgrade --install --set args={--kubelet-insecure-tls} metrics-server metrics-server/metrics-server --namespace kube-system

      - name: Install Node Exporter
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts 
          helm repo update
          helm install node-exporter prometheus-community/prometheus-node-exporter

      - name: Deploy testserver to Kubernetes
        run: |
          # Create namespace if it doesn't exist
          kubectl create namespace devzero-zxporter --dry-run=client -o yaml | kubectl apply -f -
          
          # Replace the image placeholder in the testserver Kubernetes manifest
          sed "s|\${TESTSERVER_IMG}|${{ env.TESTSERVER_IMG }}|g" test/testserver/kubernetes.yaml > testserver-k8s.yaml
          
          # Apply the testserver Kubernetes manifest
          kubectl apply -f testserver-k8s.yaml
          
          # Wait for the testserver pod to be ready
          echo "Waiting for testserver pod to be ready..."
          kubectl wait --for=condition=ready pod -l app=testserver -n devzero-zxporter --timeout=120s
          
          # Get the testserver pod name
          TESTSERVER_POD=$(kubectl get pods -n devzero-zxporter -l app=testserver -o jsonpath='{.items[0].metadata.name}')
          echo "Testserver pod: $TESTSERVER_POD"
          
          # Check the testserver logs
          echo "Testserver logs:"
          kubectl logs $TESTSERVER_POD -n devzero-zxporter

      - name: Create dztest namespace and deploy stress test pod
        run: |
          # Create dztest namespace
          kubectl create namespace dztest --dry-run=client -o yaml | kubectl apply -f -
          
          # Deploy stress test pod
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Pod
          metadata:
            name: stress-test
            namespace: dztest
          spec:
            containers:
            - name: stress
              image: ${{ env.STRESS_IMG }}
              args:
              - "--cpu"
              - "1"
              - "--vm"
              - "1"
              - "--vm-bytes"
              - "128M"
              resources:
                requests:
                  cpu: 500m
                  memory: 64Mi
                limits:
                  cpu: 2000m
                  memory: 256Mi
          EOF
          
          # Wait for the stress pod to be ready
          echo "Waiting for stress pod to be ready..."
          if ! kubectl wait --for=condition=ready pod/stress-test -n dztest --timeout=60s; then
            echo "Stress pod did not become ready within timeout. Checking events and status..."
            kubectl describe pod/stress-test -n dztest
            kubectl get events -n dztest --sort-by='.lastTimestamp' | grep stress-test
            # Continue anyway since we want to collect metrics even if the pod isn't fully ready
            echo "Continuing with test despite stress pod not being ready..."
          fi
          
          # Check the stress pod status
          kubectl get pod stress-test -n dztest -o wide

      - name: Deploy ZXporter with custom DAKR_URL and TARGET_NAMESPACES
        run: |
          # Set DAKR_URL to point to the testserver service in the same namespace
          # Set TARGET_NAMESPACES to dztest to limit collection to that namespace
          echo "Setting DAKR_URL to http://testserver.devzero-zxporter.svc.cluster.local:50051"
          echo "Setting TARGET_NAMESPACES to dztest"
          make deploy IMG=${{ env.ZXPORTER_IMG }} DAKR_URL=http://testserver.devzero-zxporter.svc.cluster.local:50051 TARGET_NAMESPACES=dztest

      - name: Wait for deployment to be ready
        run: |
          echo "Waiting for deployment to be ready..."
          kubectl wait --for=condition=available --timeout=300s deployment/devzero-zxporter-controller-manager -n devzero-zxporter || true
          
          echo "Getting pod status..."
          kubectl get pods -n devzero-zxporter -o wide
          
          echo "Describing deployment..."
          kubectl describe deployment devzero-zxporter-controller-manager -n devzero-zxporter
          
          echo "Getting pod details..."
          POD_NAME=$(kubectl get pods -n devzero-zxporter -l control-plane=controller-manager -o jsonpath='{.items[0].metadata.name}')
          kubectl describe pod $POD_NAME -n devzero-zxporter
          
          echo "Getting events for the namespace..."
          kubectl get events -n devzero-zxporter --sort-by='.lastTimestamp'
          
          echo "Checking node status..."
          kubectl describe nodes
          
          echo "Checking node resources..."
          kubectl get nodes -o custom-columns=NAME:.metadata.name,CPU:.status.capacity.cpu,MEMORY:.status.capacity.memory

      - name: Verify ZXporter is running
        run: |
          echo "Getting all devzero resource status..."
          kubectl get all -n devzero-zxporter -o wide
          
          echo "Getting pod logs (if any)..."
          POD_NAME=$(kubectl get pods -n devzero-zxporter -l control-plane=controller-manager -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME -n devzero-zxporter --tail=100 || echo "No logs available"
          
          echo "Getting pod events..."
          kubectl get events -n devzero-zxporter --field-selector involvedObject.name=$POD_NAME --sort-by='.lastTimestamp'

      - name: Wait for data collection (2 minutes)
        run: |
          echo "Waiting for 2 minutes to collect data from ZXporter..."
          sleep 120

          echo "Getting pod logs (if any)..."
          POD_NAME=$(kubectl get pods -n devzero-zxporter -l control-plane=controller-manager -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME -n devzero-zxporter --tail=100 || echo "No logs available"
          kubectl logs -n devzero-zxporter -l app.kubernetes.io/name=prometheus --all-containers


      - name: Debug Prometheus status and logs
        run: |
          PROM_POD=$(kubectl get pod -n devzero-zxporter -l app.kubernetes.io/name=prometheus,app.kubernetes.io/component=server -o jsonpath='{.items[0].metadata.name}')
          echo "Prometheus Pod: $PROM_POD"
        
          echo "Describing Prometheus pod..."
          kubectl describe pod $PROM_POD -n devzero-zxporter || echo "Describe failed"
        
          echo "Getting logs from Prometheus containers..."
          kubectl logs $PROM_POD -n devzero-zxporter -c prometheus-server || echo "No prometheus-server logs"
          kubectl logs $PROM_POD -n devzero-zxporter -c prometheus-server-configmap-reload || echo "No configmap-reload logs"
        
          echo "Spawning debug pod to test Prometheus readiness endpoint..."

          # Create a temporary curl pod
          kubectl run curlbox \
            -n devzero-zxporter \
            --image=curlimages/curl:latest \
            --restart=Never \
            --command -- sleep 120

          # Wait for it to be ready
          kubectl wait --for=condition=Ready pod/curlbox -n devzero-zxporter --timeout=30s

          # Run curl against the Prometheus /-/ready endpoint
          kubectl exec -n devzero-zxporter curlbox -- \
            curl -v http://prometheus-server.devzero-zxporter.svc.cluster.local:80/-/ready || echo "Prometheus not responding to /-/ready"

          # Clean up
          kubectl delete pod curlbox -n devzero-zxporter --ignore-not-found

          echo "Checking Prometheus config mounted in pod..."
          kubectl exec -n devzero-zxporter $PROM_POD -c prometheus-server -- cat /etc/config/prometheus.yml || echo "Could not read prometheus.yml"        
        
      - name: Check testserver stats and validate resource usage
        run: |
          echo "Checking testserver stats..."
          
          # Get the testserver pod name
          TESTSERVER_POD=$(kubectl get pods -n devzero-zxporter -l app=testserver -o jsonpath='{.items[0].metadata.name}')
          echo "Testserver pod: $TESTSERVER_POD"
          
          # Display the testserver logs
          echo "=== TESTSERVER LOGS ==="
          kubectl logs $TESTSERVER_POD -n devzero-zxporter
          echo "=== END TESTSERVER LOGS ==="
          
          # Call the stats endpoint
          echo "Calling stats endpoint..."
          
          # Create a temporary curl pod
          kubectl run curlbox \
            -n devzero-zxporter \
            --image=curlimages/curl:latest \
            --restart=Never \
            --command -- sleep 120

          # Wait for it to be ready
          kubectl wait --for=condition=Ready pod/curlbox -n devzero-zxporter --timeout=30s

          # Run curl against the stats endpoint and save to a file
          echo "=== STATS ENDPOINT RESPONSE ==="
          STATS_RESPONSE=$(kubectl exec -n devzero-zxporter curlbox -- \
            curl -s http://testserver.devzero-zxporter.svc.cluster.local:8080/stats)
          echo "$STATS_RESPONSE"
          echo "=== END STATS ENDPOINT RESPONSE ==="
          
          # Save the stats response to a file
          echo "$STATS_RESPONSE" > stats.json
          
          # Create the expected.json file with the expected pod resource usage
          cat <<EOF > expected.json
          {
            "usage_report_pods": {
              "dztest/stress-test": {
                "requests": {
                  "cpu": "500m",
                  "memory": "64Mi"
                },
                "limits": {
                  "cpu": "2000m",
                  "memory": "256Mi"
                },
                "containers": {
                  "stress": {
                    "used_cpu": "1000m",
                    "used_memory": "134217728"
                  }
                }
              }
            }
          }
          EOF
          
          # Clean up the curl pod
          kubectl delete pod curlbox -n devzero-zxporter --ignore-not-found
          
          # Check if there was any data received
          TOTAL_MESSAGES=$(echo "$STATS_RESPONSE" | grep -o '"total_messages": [0-9]*' | awk '{print $2}')
          echo "Total messages received: $TOTAL_MESSAGES"
          
          # Extract and display resource usage information if available
          echo "Checking for resource usage information..."
          
          # Check for pod usage reports
          POD_USAGE=$(echo "$STATS_RESPONSE" | grep -o '"usage_report_pods":' || echo "")
          if [ ! -z "$POD_USAGE" ]; then
            echo "✅ Pod resource usage information is available in the stats"
          else
            echo "⚠️ No pod resource usage information found"
            exit 1
          fi
          
          # Check for node usage reports
          NODE_USAGE=$(echo "$STATS_RESPONSE" | grep -o '"usage_report_nodes":' || echo "")
          if [ ! -z "$NODE_USAGE" ]; then
            echo "✅ Node resource usage information is available in the stats"
          else
            echo "⚠️ No node resource usage information found"
          fi
          
          if [ "$TOTAL_MESSAGES" -gt 0 ]; then
            echo "Testserver received data from ZXporter!"
          else
            echo "ERROR: No data received by testserver from ZXporter!"
            exit 1
          fi
          
          # Run the validator to validate the resource usage
          echo "Running validator to validate resource usage..."
          go run ./test/validator/main.go --stats=stats.json --expected=expected.json --tolerance=20
