name: 'Push zxporter to Docker Hub'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  package-and-push:
    name: Package & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Version Info
        id: version
        run: |
          GITVERSION=$(git describe --tags --always || echo "v0.0.0-$(git rev-parse --short HEAD)")
          echo "GITVERSION=${GITVERSION}" >> $GITHUB_ENV
          if [[ "$GITVERSION" =~ ^v([0-9]+)\.([0-9]+)\.(.+)$ ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            PATCH=${BASH_REMATCH[3]}
            PATCH_SHORT=${PATCH%%[-]*}
            FULLV=v${MAJOR}.${MINOR}.${PATCH_SHORT}
      
            echo "MAJOR=${MAJOR}" >> $GITHUB_ENV
            echo "MINOR=${MINOR}" >> $GITHUB_ENV
            echo "PATCH=${PATCH}" >> $GITHUB_ENV
            echo "PATCH_SHORT=${PATCH_SHORT}" >> $GITHUB_ENV
            echo "FULLV=${FULLV}" >> $GITHUB_ENV
            echo "IS_RELEASE=true" >> $GITHUB_ENV

            echo "Debug: MAJOR=${BASH_REMATCH[1]}, MINOR=${BASH_REMATCH[2]}, PATCH=${PATCH}, PATCH_SHORT=${PATCH_SHORT}"
            echo "Debug: FULLV=${FULLV}"
          else
            echo "MAJOR=0" >> $GITHUB_ENV
            echo "MINOR=0" >> $GITHUB_ENV
            echo "PATCH=0" >> $GITHUB_ENV
            echo "FULLV=v0.0.0" >> $GITHUB_ENV
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_ZXPORTER_BALANCE_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ZXPORTER_BALANCE_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set build metadata
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "GIT_TREE_STATE=clean" >> $GITHUB_ENV
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Build and push multi-arch images
        env:
          GITVERSION: ${{ env.GITVERSION }}
          MAJOR: ${{ env.MAJOR }}
          MINOR: ${{ env.MINOR }}
          PATCH: ${{ env.PATCH }}
          FULLV: ${{ env.FULLV }}
          IS_RELEASE: ${{ env.IS_RELEASE }}
          COMMIT_HASH: ${{ env.COMMIT_HASH }}
          GIT_TREE_STATE: ${{ env.GIT_TREE_STATE }}
          BUILD_DATE: ${{ env.BUILD_DATE }}
        run: |
          TAGS=("latest" "$(git rev-parse --short HEAD)" "$GITVERSION")

          if [[ "$IS_RELEASE" == "true" ]]; then
            TAGS+=("$FULLV")
          fi

          for tag in "${TAGS[@]}"; do
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --push \
              -t devzeroinc/zxporter:$tag \
              --build-arg TARGETOS \
              --build-arg TARGETARCH \
              --build-arg MAJOR=$MAJOR \
              --build-arg MINOR=$MINOR \
              --build-arg PATCH=$PATCH \
              --build-arg GITVERSION=$GITVERSION \
              --build-arg COMMIT_HASH=$COMMIT_HASH \
              --build-arg GIT_TREE_STATE=$GIT_TREE_STATE \
              --build-arg BUILD_DATE=$BUILD_DATE \
              .
          done